

CREATE TABLE status_types(
                             status_type_id VARCHAR2(255),
                             status_name VARCHAR2(255),
                             creation_date                DATE default SYSDATE not null,
                             created_by                   VARCHAR2(50) default USER not null,
                             last_update_date             DATE default SYSDATE NOT NULL,
                             last_updated_by              VARCHAR2(50) default USER not null,
                             created_by_fullname          VARCHAR2(300),
                             CONSTRAINT status_types_pk PRIMARY KEY(status_type_id)
);



CREATE TABLE users(
                      user_id NUMBER(13) GENERATED BY DEFAULT AS IDENTITY,
                      username VARCHAR2(255),
                      birth_date DATE,
                      is_internal NUMBER(1) DEFAULT 1 NOT NULL,
                      creation_date                DATE default SYSDATE not null,
                      created_by                   VARCHAR2(50) default USER not null,
                      last_update_date             DATE default SYSDATE NOT NULL,
                      last_updated_by              VARCHAR2(50) default USER not null,
                      created_by_fullname          VARCHAR2(300),
                      CONSTRAINT users_pk PRIMARY KEY(user_id)

);





CREATE TABLE tasks(
                      task_id NUMBER(13) GENERATED BY DEFAULT AS IDENTITY,
                      name VARCHAR2(500) NOT NULL,
                      status_type_id VARCHAR2(255),
                      user_id NUMBER(13),
                      due_date DATE,
                      created_by VARCHAR2(50) DEFAULT USER,

                      CONSTRAINT tasks_pk PRIMARY KEY(task_id),
                      CONSTRAINT task_statuses_fk FOREIGN KEY(status_type_id) REFERENCES status_types(status_type_id),
                      CONSTRAINT task_users_fk FOREIGN KEY(user_id) REFERENCES users(user_id)
);


ALTER TABLE tasks ADD(
creation_date                DATE default SYSDATE not null,
last_update_date             DATE default SYSDATE NOT NULL,
last_updated_by              VARCHAR2(50) default USER not null,
created_by_fullname          VARCHAR2(300)
);

ALTER TABLE tasks
    RENAME COLUMN tasks_name TO task_name;


INSERT INTO status_types(status_type_id,status_name, created_by_fullname)
VALUES(SYS_GUID(), 'Pending', USER );

INSERT INTO status_types(status_type_id,status_name, created_by_fullname)
VALUES(SYS_GUID(), 'In progress', USER );

SELECT * FROM STATUS_TYPES;
DELETE FROM STATUS_TYPES WHERE STATUS_NAME = 'Cancelled';

INSERT INTO status_types(status_type_id,status_name, created_by_fullname)
VALUES(SYS_GUID(), 'Cancelled', USER );


INSERT INTO users(username,birth_date,created_by_fullname)
VALUES('vali1', TO_DATE('2005-06-01', 'YYYY-MM-DD'), USER );

INSERT INTO users(username,birth_date,created_by_fullname)
VALUES('vali2', TO_DATE('2005-06-03', 'YYYY-MM-DD'), USER );

INSERT INTO users(username,birth_date,created_by_fullname)
VALUES('vali3', TO_DATE('2005-06-04', 'YYYY-MM-DD'), USER );

SELECT * FROM users;




SELECT * FROM STATUS_TYPES;
TRUNCATE TABLE tasks;
INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, creation_date, created_by_fullname) VALUES ('Revizuirea documentației', (SELECT status_type_id FROM status_types WHERE status_name = 'Pending'), 1, TO_DATE('2023-10-05', 'YYYY-MM-DD'), 'Ioana', SYSDATE, 'SUMMER_SCHOOL');​
INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, created_by_fullname) VALUES ('Testarea aplicației', (SELECT status_type_id FROM status_types WHERE status_name = 'In progress'), 2, SYSDATE, 'Alice', 'SUMMER_SCHOOL');
INSERT INTO tasks (task_name, status_type_id, user_id, due_date, created_by, creation_date, created_by_fullname) VALUES ('Finalizarea raportului de vânzări', (SELECT status_type_id FROM status_types WHERE status_name = 'Cancelled'), 3, TO_DATE('2025-08-05', 'YYYY-MM-DD'), 'Catalin', SYSDATE, 'SUMMER_SCHOOL');




UPDATE tasks SET due_date = TO_DATE('2023-10-05', 'YYYY-MM-DD') WHERE task_id= 1;
UPDATE tasks SET due_date = TO_DATE('2023-10-05', 'YYYY-MM-DD') WHERE CREATED_BY='Ioana';


CREATE OR REPLACE VIEW active_tasks_v AS
SELECT task_id, task_name, due_date
FROM tasks T
         JOIN status_types S ON T.STATUS_TYPE_ID = S.STATUS_TYPE_ID
WHERE status_name IN ('In Progress', 'Not Started');


CREATE OR REPLACE FUNCTION get_task_status(task_id_input NUMBER)
RETURN VARCHAR2AS task_status_output VARCHAR2(255);
BEGIN SELECT ST.status_name INTO task_status_output
      FROM status_typesST JOIN tasks T ON ST.STATUS_TYPE_ID = T.STATUS_TYPE_ID
      WHERE T.task_id= task_id_input;
RETURN task_status_output;
END;


SELECT * FROM USERS u ;

INSERT INTO users(username,birth_date,created_by_fullname)
VALUES ('vali4', TO_DATE('2003-03-01', 'YYYY-MM-DD'), USER);

INSERT INTO users(username,birth_date,created_by_fullname)
VALUES ('vali5', TO_DATE('2003-04-01', 'YYYY-MM-DD'), USER);


SELECT * FROM TASKS t ;

INSERT INTO tasks(task_name, status_type_id, user_id, due_date, created_by,creation_date,created_by_fullname)
VALUES ('Rezolvarea de bugs', (SELECT status_type_id FROM status_types WHERE status_name = 'Pending'), 2, TO_DATE('2027-03-01', 'YYYY-MM-DD'), USER, SYSDATE, 'Danciu Valentin');

INSERT INTO tasks(task_name, status_type_id, user_id, due_date, created_by,creation_date,created_by_fullname)
VALUES ('Adaugare de features', (SELECT status_type_id FROM status_types WHERE status_name = 'Not Started'), 2, TO_DATE('2027-03-01', 'YYYY-MM-DD'), USER, SYSDATE, 'Danciu Valentin');


--tema
SELECT * FROM TASKS t
WHERE t.STATUS_TYPE_ID = (
    SELECT STATUS_TYPE_ID  FROM STATUS_TYPES st
    WHERE st.STATUS_NAME = 'Pending' ) AND
    t.DUE_DATE = TO_DATE('05-08-2025', 'DD-MM-YYYY');


SELECT * FROM TASKS t
                  JOIN STATUS_TYPES st ON t.STATUS_TYPE_ID  = st.STATUS_TYPE_ID
WHERE st.status_name = 'In progress'
GROUP BY t.USER_ID



SELECT * FROM USERS u
                  JOIN TASKS t ON u.USER_ID = t.USER_ID
                  JOIN STATUS_TYPES st ON t.STATUS_TYPE_ID = st.STATUS_TYPE_ID
WHERE st.STATUS_NAME = 'In progress' AND TRUNC(MONTHS_BETWEEN(u.BIRTH_DATE , SYSDATE )/12)>30;



CREATE OR REPLACE PROCEDURE sterge_cancelled AS
BEGIN
DELETE FROM tasks
WHERE status_type_id = (
    SELECT status_type_id
    FROM status_types
    WHERE status_name = 'Cancelled'
)
  AND SYSDATE - due_date >= 3;

COMMIT;
END;



